name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # required for `npm publish --provenance`

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        # no "version" here; it will use package.json's "packageManager"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git (for standard-version)
        run: |
          git config --global user.email "liaqatsaeed007@gmail.com"
          git config --global user.name "Liaqat Saeed"

      - name: Build package
        run: pnpm run build

      - name: Bump version and generate changelog
        run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push version bump & tags
        run: git push origin HEAD:main --follow-tags

      - name: Publish package (with provenance)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
